// <auto-generated />
using System;
using Ampara.Infra.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ampara.Infra.Dados.Migracoes
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618224814_AdicionarInformacoesClinicas")]
    partial class AdicionarInformacoesClinicas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ampara.Dominio.Entidades.ConvitePaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("convites_paciente", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.HabitoDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Agua")
                        .HasColumnType("integer")
                        .HasColumnName("agua");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<bool>("Exercitou")
                        .HasColumnType("boolean")
                        .HasColumnName("exercitou");

                    b.Property<int>("HorasSono")
                        .HasColumnType("integer")
                        .HasColumnName("horas_sono");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<int>("QualidadeSono")
                        .HasColumnType("integer")
                        .HasColumnName("qualidade_sono");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "Data")
                        .IsUnique();

                    b.ToTable("habitos_diarios", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.InformacaoClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string[]>("DiagnosticosPersonalizados")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("diagnosticos_personalizados");

                    b.Property<string[]>("DiagnosticosPrincipais")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("diagnosticos_principais");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("SexoBiologico")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sexo_biologico");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("informacoes_clinicas", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("CadastradoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("cadastrado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dosagem");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("horario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("CadastradoPor");

                    b.HasIndex("PacienteId");

                    b.ToTable("medicamentos", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EnviadoPeloPaciente")
                        .HasColumnType("boolean")
                        .HasColumnName("enviado_pelo_paciente");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lida");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "ProfissionalId");

                    b.ToTable("mensagens", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.NotaClinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataSessao")
                        .HasColumnType("date")
                        .HasColumnName("data_sessao");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<DateOnly?>("ProximaSessao")
                        .HasColumnType("date")
                        .HasColumnName("proxima_sessao");

                    b.Property<string>("TipoSessao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_sessao");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("notas_clinicas", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.NotaCofre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("notas_cofre", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primeiro_nome");

                    b.Property<string>("RegistroProfissional")
                        .HasColumnType("text")
                        .HasColumnName("registro_profissional");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sobrenome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.RegistroHumor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anotacao")
                        .HasColumnType("text")
                        .HasColumnName("anotacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string[]>("Fatores")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fatores");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer")
                        .HasColumnName("pontuacao");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId", "Data")
                        .IsUnique();

                    b.ToTable("registros_humor", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.RegistroMedicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<Guid>("MedicamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicamento_id");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<bool>("Tomado")
                        .HasColumnType("boolean")
                        .HasColumnName("tomado");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("MedicamentoId", "Data")
                        .IsUnique();

                    b.ToTable("registros_medicamento", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.VinculoProfissionalPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId", "PacienteId")
                        .IsUnique();

                    b.ToTable("vinculos_profissional_paciente", (string)null);
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.ConvitePaciente", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Profissional")
                        .WithMany("ConvitesEnviados")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.HabitoDiario", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("HabitosDiarios")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.InformacaoClinica", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithOne("InformacaoClinica")
                        .HasForeignKey("Ampara.Dominio.Entidades.InformacaoClinica", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Medicamento", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("CadastradoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("Medicamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.NotaClinica", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("NotasClinicasComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Profissional")
                        .WithMany("NotasClinicasComoAutor")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.NotaCofre", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("NotasCofre")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.RegistroHumor", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("RegistrosHumor")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.RegistroMedicamento", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Medicamento", "Medicamento")
                        .WithMany("Registros")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ampara.Dominio.Entidades.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.VinculoProfissionalPaciente", b =>
                {
                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Paciente")
                        .WithMany("VinculosComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ampara.Dominio.Entidades.Perfil", "Profissional")
                        .WithMany("VinculosComoProfissional")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Medicamento", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Ampara.Dominio.Entidades.Perfil", b =>
                {
                    b.Navigation("ConvitesEnviados");

                    b.Navigation("HabitosDiarios");

                    b.Navigation("InformacaoClinica");

                    b.Navigation("Medicamentos");

                    b.Navigation("NotasClinicasComoAutor");

                    b.Navigation("NotasClinicasComoPaciente");

                    b.Navigation("NotasCofre");

                    b.Navigation("RegistrosHumor");

                    b.Navigation("VinculosComoPaciente");

                    b.Navigation("VinculosComoProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
